export { parseAssistantMessageV2 } from "./parse-assistant-message";
export const toolParamNames = [
    "command",
    "requires_approval",
    "path",
    "absolutePath",
    "content",
    "diff",
    "regex",
    "file_pattern",
    "recursive",
    "action",
    "url",
    "coordinate",
    "text",
    "server_name",
    "tool_name",
    "arguments",
    "uri",
    "question",
    "options",
    "response",
    "result",
    "context",
    "title",
    "what_happened",
    "steps_to_reproduce",
    "api_request_output",
    "additional_context",
    "needs_more_exploration",
    "task_progress",
    "timeout",
    "input",
    "from_ref",
    "to_ref",
];
//# sourceMappingURL=index.js.map